name: homework 62
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  my_first_job:
    name: My First Job
    runs-on: ubuntu-latest
    environment: dev
    outputs:

      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT
      env:
        MY_SECRET: ${{ secrets.SECRET1 }}
        MY_VAR: ${{ vars.dev }}

  my_second_job:
    name: My Second Job
    runs-on: ubuntu-latest
    needs: my_first_job  # This job will only run if the first job is successful
    environment: dev
    steps:
    - run: |
        # Create local variables from job outputs
        output1="${{ needs.my_first_job.outputs.output1 }}"
        output2="${{ needs.my_first_job.outputs.output2 }}"

        # Echo the variables
        echo "Output 1: $output1"
        echo "Output 2: $output2"
      env:
          MY_SECRET: ${{ secrets.SECRET1 }}
          MY_VAR: ${{ vars.dev }}